### ISSUE TITLE
Have you tried RGB+Lidar semantic segmentation on the KITTI-360 dataset? How should I modify it? 

### ISSUE THREAD

**Issue by ascacdsaa** [JiaDingCN/GeminiFusion#4]
Very great job, have you tried RGB+Lidar semantic segmentation on the KITTI-360 dataset? How should I modify it? Can you provide some suggestions? Looking forward to your reply, thank you!!!

**Comment by JiaDingCN** [comment]
Thank you for your interest in our work! Due to time and resource limitation, we did not try the  KITTI-360 semantic segmentation task. But it would not be hard to do that: [CMNeXt] is able to do the KITTI-360 semantic segmentation and we have already [applied our GeminiFusion into it](https://github.com/JiaDingCN/GeminiFusion/tree/DeLiVER). I believe that with only minor tweaks, our code will work on the KITTI-360 dataset, but some of the hyper-parameters may need to be tweaked for optimal performance. You are more than welcome to experiment with our code.
